CREATE VIEW EMP_VIEW
AS
SELECT empno,ename,sal,job,deptno
FROM emp
WHERE job = 'SALESMAN'

SELECT * 
FROM EMP_VIEW

UPDATE EMP_VIEW SET SAL=0 WHERE ENAME=='MARTIN';
--1행이 업데이트 되었습니다.



--복합뷰
CREATE VIEW EMP_VIEW2
AS
SELECT deptno, ROUND(AVG(SAL)) 평균월급 --별명없으면error
FROM EMP
GROUP BY deptno

SELECT * FROM EMP_VIEW2



SELECT E.ENAME, E.SAL, E.DEPTNO, V.평균월급
FROM EMP E, (
	SELECT E2.DEPTNO, ROUND(AVG(E2.SAL)) 평균월급
	FROM EMP E2
	GROUP BY E2.DEPTNO) V
WHERE E.DEPTNO = V.DEPTNO
AND E.SAL > V. 평균월급;


SELECT E.ENAME, E.SAL, E.DEPTNO, V.평균월급
FROM EMP E, (EMP_VIEW2) V
WHERE E.DEPTNO = V.DEPTNO
AND E.SAL > V. 평균월급;