--ROW_NUMBER
SELECT ename,sal,
	ROW_NUMBER ()
	OVER(ORDER BY SAL DESC) 
FROM EMP



--[6] FIRST_VALUE
SELECT DEPTNO,ENAME,SAL,
	FIRST_VALUE(ENAME)
	OVER(PARTITION BY DEPTNO
	ORDER BY SAL DESC 
	ROWS UNBOUNDED PRECEDING ) AS ENAME_FV
FROM EMP



--[7] LAST_VALUE 
SELECT DEPTNO,ENAME,SAL,
	LAST_VALUE(ENAME)
	OVER(PARTITION BY DEPTNO
	ORDER BY SAL DESC
	ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING )
	AS ENAME_FV
FROM EMP



--[8] LAG (46)
SELECT ENAME, HIREDATE, SAL,
	LAG(SAL) OVER(ORDER BY HIREDATE)
	AS LAG_SAL
FROM EMP
WHERE JOB='SALESMAN';


SELECT ENAME, HIREDATE, SAL,
	LAG(SAL) OVER(ORDER BY HIREDATE)
	AS LAG_SAL
FROM EMP
WHERE JOB='SALESMAN';



--[9] LEAD (46)
SELECT ENAME,HIREDATE,SAL
	,LEAD(SAL) 
	OVER(ORDER BY HIREDATE) 
	AS LAG_SAL
FROM EMP
WHERE JOB='SALESMAN';



--[10] RATIO_TO_REPORT (51)
SELECT ENAME,JOB,SAL,
			ROUND(RATIO_TO_REPORT(SAL)
			OVER(),2)AS RATIO_TO_REPORT 
		FROM EMP
		WHERE JOB='SALESMAN'
		ORDER BY SAL -- RATIO_TO-REPORT



--[11] PERCENT_RANK
SELECT DEPTNO,ENAME,SAL,
	PERCENT_RANK()
	OVER(PARTITION BY DEPTNO
	ORDER BY SAL DESC) 
	AS PR
FROM EMP;


--[12] CUME_DIST \
SELECT DEPTNO,ENAME,SAL,
	ROUND(CUME_DIST()
	OVER(PARTITION BY DEPTNO
	ORDER BY SAL DESC),2)
	AS CD
FROM EMP



--[13] NTILE(43)
SELECT ENAME,SAL,
	NTILE(4) OVER(ORDER BY SAL DESC) AS TILE
FROM EMP;