--SUM
SELECT ename,JOB,SAL,SUM(SAL) 
	OVER (PARTITION BY JOB
			ORDER BY SAL DESC 
	ROWS UNBOUNDED PRECEDING) AS  SUM_SAL
FROM EMP;

SELECT JOB,ENAME,SAL,
	SUM(SAL) 
	OVER (
	ORDER BY SAL  
	ROWS 1 PRECEDING) AS  SUM_SAL
FROM EMP;


SELECT JOB,ENAME,SAL,
	SUM(SAL) 
	OVER (
	ORDER BY SAL  
	ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) 
	AS  SUM_SAL
FROM EMP;

--RANGE
SELECT JOB, ENAME,SAL,
	SUM(SAL)OVER(ORDER BY SAL 
	RANGE 150 PRECEDING)
	AS CUME_SAL
FROM EMP
WHERE JOB='CLERK' OR JOB = 'SALESMAN'

--RANK
SELECT ENAME,SAL
	,RANK()OVER(ORDER BY SAL)
	AS RANK 
FROM EMP


SELECT ENAME,SAL
	,RANK()OVER(ORDER BY SAL)
	AS RANK 
FROM EMP


SELECT ENAME,SAL
	,RANK()OVER(ORDER BY SAL)
	AS RANK 
FROM EMP

--DENSE_RANK
SELECT ename,sal,
	DENSE_RANK()
	OVER(ORDER BY SAL DESC) AS RANK
FROM EMP


